# FROM node:alpine3.13

# ENV NODE_VERSION=14.15.4
# ENV NODE_ENV=staging
# ENV TZ=Asia/Tokyo

# RUN apk add --no-cache alpine-sdk linux-headers libxml2-dev tzdata \
#     gcc libc-dev gmp-dev sudo bash curl vim git wget && \
#     apk add --virtual build-dependencies --no-cache build-base curl-dev && \
#     # create application
#     cd /var && mkdir -p www/html/app && \
#     cd www/html/app/ && \
#     git clone --depth 1 https://b9ca610614485d8b568ef218195d3f0ba0b1fa64:x-oauth-basic@github.com/yochiba/tech_project_app.git && \
#     cd /var/www/html/app/tech_project_app/ && \
#     sudo rm -rf api_server document mysql nginx redis && \
#     sudo rm -f docker-compose.yml docker-compose-stg.yml && \
#     cd client

# WORKDIR /var/www/html/app/tech_project_app/client

# COPY ./.env.staging /var/www/html/app/tech_project_app/client
# COPY ./entrypoint-prod.sh /usr/bin/
# RUN chmod +x /usr/bin/entrypoint-prod.sh
# ENTRYPOINT ["entrypoint-prod.sh"]

# EXPOSE 3000
FROM nginx:alpine

ENV NODE_VERSION=14.15.4
ENV NODE_ENV=staging
ENV TZ=Asia/Tokyo
ENV LANG ja_JP.UTF-8
ENV LC_TIME C

RUN apk add --no-cache alpine-sdk linux-headers libxml2-dev tzdata \
    gcc libc-dev gmp-dev sudo bash curl vim git wget nodejs npm && \
    apk add --virtual build-dependencies --no-cache build-base curl-dev && \
    touch ~/.bashrc && \
    curl -o- -L https://yarnpkg.com/install.sh | bash && \
    ln -s "$HOME/.yarn/bin/yarn" /usr/local/bin/yarn && \
    sudo rm -f /etc/nginx/conf.d/default.conf && \
    sudo rm -f /etc/nginx/nginx.conf && \
    # create application
    cd /var && mkdir -p www/html/app && \
    cd www/html/app/ && \
    git clone --depth 1 https://b9ca610614485d8b568ef218195d3f0ba0b1fa64:x-oauth-basic@github.com/yochiba/tech_project_app.git && \
    cd /var/www/html/app/tech_project_app/ && \
    sudo rm -rf api_server document mysql nginx redis && \
    sudo rm -f docker-compose.yml docker-compose-stg.yml && \
    cd client

# Nginx
COPY ./nginx/nginx.conf /etc/nginx/
COPY ./nginx/techies_guild_stg.conf /etc/nginx/conf.d/

# Client
COPY ./.env.staging /var/www/html/app/tech_project_app/client
COPY ./entrypoint-prod.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint-prod.sh
ENTRYPOINT ["entrypoint-prod.sh"]

# WORKDIR /etc/nginx/conf.d
WORKDIR /var/www/html/app/tech_project_app/client

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]