FROM nginx:alpine

WORKDIR /etc/nginx/conf.d

ENV TZ=Asia/Tokyo
ENV LANG ja_JP.UTF-8
ENV LC_TIME C

RUN apk add --no-cache alpine-sdk linux-headers libxml2-dev tzdata \
    gcc libc-dev gmp-dev sudo bash curl vim git wget && \
    apk add --virtual build-dependencies --no-cache build-base curl-dev && \
    sudo rm -f /etc/nginx/conf.d/default.conf && \
    sudo rm -f /etc/nginx/nginx.conf && \
    mkdir -p　/var/www/html/app/tech_project_app/

COPY ../client /var/www/html/app/tech_project_app/
COPY ./nginx.conf /etc/nginx/
COPY ./techies_guild_stg.conf /etc/nginx/conf.d/

COPY ../client/entrypoint-prod.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint-prod.sh

ENTRYPOINT ["entrypoint-prod.sh"]

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]