FROM nginx:alpine

WORKDIR /etc/nginx/conf.d

ENV TZ=Asia/Tokyo
ENV LANG ja_JP.UTF-8
ENV LC_TIME C
ENV API_SERVER_HOST=http://api_server_stg:3001
ENV CLIENT_HOST=http://client_stg:3000
ENV HOST_URL=yocoder-staging.site

RUN apk add --no-cache alpine-sdk linux-headers libxml2-dev tzdata \
    gcc libc-dev gmp-dev sudo bash curl vim git wget && \
    apk add --virtual build-dependencies --no-cache build-base curl-dev && \
    sudo rm -f /etc/nginx/conf.d/default.conf && \
    sudo rm -f /etc/nginx/nginx.conf

COPY ./nginx.conf /etc/nginx/
COPY ./conf.d/techies_guild.conf /etc/nginx/conf.d/

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]