FROM mysql:8.0.22

ENV MYSQL_ROOT_PASSWORD=ra_8EevEJRP!
ENV MYSQL_USER=root
ENV TZ=Asia/Tokyo

RUN apt update -qq && apt install -y sudo vim

EXPOSE 3306

COPY ./my.cnf /etc/mysql/conf.d/my.cnf

CMD ["mysqld"]