FROM ruby:2.7.2-alpine

ENV DOCKER_ENV=staging
ENV CORS_ALLOWED_ORIGINS_HOST=http://yocoder-staging.site
ENV MYSQL_USERNAME=root
ENV MYSQL_PASSWORD=ra_8EevEJRP!
ENV MYSQL_HOST=mysql_stg
ENV MYSQL_PORT=3306
ENV REDIS_HOST=redis_stg
ENV REDIS_PORT=6379
ENV TZ=Asia/Tokyo
ENV DOCKERIZE_VERSION v0.6.1

RUN apk add --no-cache alpine-sdk linux-headers libxml2-dev make tzdata \
    gcc libc-dev gmp-dev sudo bash curl vim git nodejs npm mysql-client mysql-dev wget && \
    apk add --virtual build-dependencies --no-cache build-base curl-dev && \
    wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
    tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
    rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && \
    touch ~/.bashrc && \
    curl -o- -L https://yarnpkg.com/install.sh | bash && \
    ln -s "$HOME/.yarn/bin/yarn" /usr/local/bin/yarn && \
    # apiアプリケーション作成
    cd /var && mkdir -p www/html/app && \
    cd www/html/app && \
    git clone --depth 1 https://b9ca610614485d8b568ef218195d3f0ba0b1fa64:x-oauth-basic@github.com/yochiba/tech_project_app.git && \
    cd /var/www/html/app/tech_project_app && \
    rm -rf client document mysql nginx redis && \
    rm -f docker-compose.yml docker-compose-stg.yml && \
    cd api_server/ && \
    bundle install

WORKDIR /var/www/html/app/tech_project_app/api_server

# COPY ./config/credentials/staging.yml.enc /var/www/html/app/tech_project_app/api_server/config/credentials.yml.enc
COPY ./config/database.yml /var/www/html/app/tech_project_app/api_server/config/

COPY ./entrypoint.sh /usr/bin/
RUN chmod +x /usr/bin/entrypoint.sh
ENTRYPOINT ["entrypoint.sh"]

EXPOSE 3001
